### ISSUE TITLE
Where to find code for the lessons?

### ISSUE THREAD

**Issue by budarin** [reactjs/react-router-tutorial#104]
Could you provide code for the lessons?
Thanks

**Comment by andrewcoelho** [comment]
The code for the lessons is currently stored in a series of commits. You can find this code by running ```git checkout <previous lesson final sha>``` from your terminal. Or you can look at the commit history here on github on the master branch where you'll see all the code changes for each lesson.

If you look at my pull request #100, you will see that this repositories structure is being changed to make navigating between lessons easier. You can also check out my fork of the tutorial until the pull request is merged; it has the new structure with the full code for each lesson in its own folder.

**Comment by budarin** [comment]
thanks!
but for brginners its too complicated to such code discovering)
