### ISSUE TITLE
Lesson 9 - Missing import

### ISSUE THREAD

**Issue by deviantony** [reactjs/react-router-tutorial#117]
In the IndexLink example, it misses the import.

```javascript
import { Link, IndexLink } from 'react-router';
```

**Comment by bfink13** [comment]
What file? I think you're supposed to add it yourself as part of going through the lessons.

**Comment by deviantony** [comment]
In the `App.js` file, under the **IndexLink** section.

As every other imports were specified during the previous steps of the tutorial, I thought that this was an issue.
