### ISSUE TITLE
No response on port 8080

### ISSUE THREAD

**Issue by getsetbro** [reactjs/react-router-tutorial#121]
This probably isn't your issue to solve but you're smart people and it seems to be a barrier for a lot of folks and those who want to run the tutorial. When I run the first lesson I see nothing on localhost:8080. I do however see the app when I hit it using http://127.0.0.1:8080. I have run commands and found nothing else is using that port.
`COMMAND   PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME`
`node    17400 getsetbro   27u  IPv4 0x3f582051c499540f      0t0  TCP localhost:http-alt (LISTEN) `
In fact if I use httpster to host an app there is no issue. One option is to configure webpack to use a different port. So maybe it is the way webpack runs node right now?

**Comment by bfink13** [comment]
I just installed the project for the first time and have no issues running on localhost or 127.0.0.1.
