### ISSUE TITLE
06-Params - IndexRoute Is Not Defined

### ISSUE THREAD

**Issue by joemccann** [reactjs/react-router-tutorial#130]
```
<IndexRoute component={Home}/>
```

is added in the code snippet a bit too early.

It causes this error:

```
Uncaught ReferenceError: IndexRoute is not defined
```

**Comment by mshibl** [comment]
+1

**Comment by dyoxyne** [comment]
+1
I also encountered this issue.

**Comment by yurizhang** [comment]
import { Router, Route, hashHistory, **IndexRoute** } from 'react-router'; 

**IndexRoute** need to import first.
