### ISSUE TITLE
server rendering (from lesson 14)

### ISSUE THREAD

**Issue by sosnovskyas** [reactjs/react-router-tutorial#134]
Has trouble with rendering in server side. It's clearly visible with disabled js in browser. Index route didn't rendering if we send static by nodejs server.
But if line (https://github.com/reactjs/react-router-tutorial/blob/master/lessons/14-whats-next/server.js#L14) commented, rendering in server side work good.

**Comment by timdorr** [comment]
You can remove `public/index.html` as well. A PR to fix this would be great!
