### ISSUE TITLE
06-params What is the best way for populate individual content in Repo.js

### ISSUE THREAD

**Issue by seeliang** [reactjs/react-router-tutorial#135]
Hi, guys 

thank you for the tutorial, 
and this is the one i been waiting for.

as i mentioned in title, 

```html
// ./modules/Repo.js
<div>
        <h2>{this.props.params.repoName}</h2>
        <p>{this.props.params.userName}</p>
        // From this point two repos (react/react-router) should have different content 
</div>
```

Not sure how and where should i populate content, 
in Repo.js or Repos.js?  use props?

could anyone give me a hint?
@andrewcoelho 

many thanks

**Comment by timdorr** [comment]
You should do that in Repo.js. It will get the props from the router and can use that to grab any data it needs and store that in local state. (Eventually, you can see about storing that state globally in something like Redux, but it's not needed right now).

**Comment by seeliang** [comment]
thanks for the info @timdorr :)
