### ISSUE TITLE
How to disappear url hash in express server

### ISSUE THREAD

**Issue by EasonWang01** [reactjs/react-router-tutorial#143]
Hi,thanks for reply.

Now I can hide the hash,but when I refresh it will says cannot get.
I saw the tutorial using webpack dev server,than using `historyApiFallback:true`
but how to do the same in express server?

**Comment by timdorr** [comment]
As long as you've got the `app.get('*'` part in there, it will accept all routes through the router. Just make sure you're using a `browserHistory` as well.
