### ISSUE TITLE
13-server-rendering if i disable Javascript 

### ISSUE THREAD

**Issue by seeliang** [reactjs/react-router-tutorial#144]
i am working on L13, 

```JavaScript
npm run start:prod
```
if i disable Javascript, i will get a empty page
```html
<div id="app"></div>
```
is this right?

**Comment by timdorr** [comment]
By the end of it, you won't have that problem. It will look like lesson 14.

**Comment by seeliang** [comment]
sorry, i asked wrong question 

should be 
https://github.com/reactjs/react-router-tutorial/issues/159
