### ISSUE TITLE
npm ERR! weird error 127

### ISSUE THREAD

**Issue by MuhammadTamzid** [reactjs/react-router-tutorial#154]
after run ``npm start``
raise this error 
``
tam@tam-G41-M7:~/workspace/react/react-router-tutorial/lessons/01-setting-up$ npm start

> tutorial@1.0.0 start /home/tam/workspace/react/react-router-tutorial/lessons/01-setting-up
> webpack-dev-server --inline --content-base .

/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
``

**Comment by SSalekin** [comment]
The nodejs comes by default with your OS (ubuntu 14 lts) is outdated. Please try reinstalling nodejs lts version:
...
Remove old nodejs:
------------------------
sudo npm uninstall npm -g rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/npm*
sudo apt-get remove nodejs

Install Nodejs 4 LTS:
--------------------------
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
...
