### ISSUE TITLE
Lesson 5 - Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `App`.

### ISSUE THREAD

**Issue by mathieusteele** [reactjs/react-router-tutorial#155]
In lesson 5, after adding NavLink components, rendering fails with the following error

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `App`.

**Comment by timdorr** [comment]
Make sure you are adding the import statement for `NavLink`.

**Comment by guyueping** [comment]
i met the same error, have you solve it?
