### ISSUE TITLE
Pretty URLs when the node server that serves your index.html also serves your backend API?

### ISSUE THREAD

**Issue by scwood** [reactjs/react-router-tutorial#156]
I didn't see anything about this in the documentation.

To get browser history to work the documentation says you need to do the following:

```js
// send all requests to index.html so browserHistory in React Router works
app.get('*', function (req, res) {
  res.sendFile(path.join(__dirname, 'index.html'))
})
```

As I said in the title what if that node server is also serving my backend API? Do I need to have two different servers in production?

**Comment by timdorr** [comment]
Nope, just have that rule placed after the API stuff. Even better, use a separate express Router for your API stuff. As long as it's mounted before this catch-all, it will run first and not run this route.
