### ISSUE TITLE
single package.json

### ISSUE THREAD

**Issue by hozefaj** [reactjs/react-router-tutorial#161]
Whats the reasoning to have individual package.json per lesson?  Its just a unnecessary overhead in installing the same modules 14 times.

Doesn't having one for the entire series works better?

**Comment by xiaopow** [comment]
You can just delete the entire tutorial folder afterwards.

**Comment by timdorr** [comment]
@hozefaj It's supposed to represent your project as you go. You'll add/remove/change deps while building an application normally, so each lesson is a checkpoint along that journey. Also, we don't want to explain why you're adding something before you use it.
