### ISSUE TITLE
question about 13-server-rendering

### ISSUE THREAD

**Issue by gdq** [reactjs/react-router-tutorial#162]
Hi,

I was wondering if in server.js, the html constant it says:
...
&lt;script src="/bundle.js"&gt;&lt;/script&gt;
...
Should this not be:
 &lt;script src="/server.bundle.js"&gt;&lt;/script&gt;
as specified in the webpack.config.server.js

Best regards,

geert

**Comment by xiaopow** [comment]
@gdq 

This is the HTML render template that the server is sending to the client. It is similar to index.html so it is linking the bundle.js for the browser. server.bundle.js is used to start the node server. So the original is correct.
