### ISSUE TITLE
Error on npm start?

### ISSUE THREAD

**Issue by VikR0001** [reactjs/react-router-tutorial#164]
Afer installing lesson one with no errors, I ran npm start and got the following error:

> tutorial@1.0.0 start /Applications/MeteorWebApps/react-router-tutorial/lessons/01-setting-up
> webpack-dev-server --inline --content-base .
> 
> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE 127.0.0.1:8080
>     at Object.exports._errnoException (util.js:849:11)
>     at exports._exceptionWithHostPort (util.js:872:20)
>     at Server._listen2 (net.js:1231:14)
>     at listen (net.js:1267:10)
>     at net.js:1376:9
>     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
> 

> 
> ...
> 
> Tell the author that this fails on your system:
> 
> 

> npm ERR!     webpack-dev-server --inline --content-base .

How can I correct this? Thanks in advance for the info.

**Comment by timdorr** [comment]
You're already running something on port 8080. Shut that down.
