### ISSUE TITLE
error "404 - File or directory not found." when publishing on iis 

### ISSUE THREAD

**Issue by szare** [reactjs/react-router-tutorial#166]
I'm trying to bublish lesson 12 on iis server, but following error appears when I try to open a link in new tab or refresh the page:
**404 - File or directory not found.**
_The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable._
The sample working properly on localhost, my problem is when I copy the bundle.js and the Index.html to the iis server in windows server 2012.
Do you have any sugestion?

**Comment by timdorr** [comment]
You need to configure it to route all requests to the index.html file. I'm not sure how that's done in IIS, but it's a configuration issue.

**Comment by szare** [comment]
@timdorr , thank you.
I used the following config in my MVC project's routing to manage the route, and the issue solved:

  public class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            routes.MapRoute(
                name: "Default",
                url: "*",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional });

            routes.MapRoute("React failover", "{*uri}", new { controller = "Home", action = "Index" });
        }
    }
