### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by choukin** [reactjs/react-router-tutorial#169]
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@2.14.20
> 3 info using node@v4.4.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart tutorial@1.0.0
> 6 info start tutorial@1.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info tutorial@1.0.0 Failed to exec start script
> 9 verbose stack Error: tutorial@1.0.0 start: `webpack-dev-server --hot`
> 9 verbose stack Exit status 3221225501
> 9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:827:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 10 verbose pkgid tutorial@1.0.0
> 11 verbose cwd D:\git\react-router-tutorial\lessons\01-setting-up
> 12 error Windows_NT 6.1.7600
> 13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 14 error node v4.4.0
> 15 error npm  v2.14.20
> 16 error code ELIFECYCLE
> 17 error tutorial@1.0.0 start: `webpack-dev-server --hot`
> 17 error Exit status 3221225501
> 18 error Failed at the tutorial@1.0.0 start script 'webpack-dev-server --hot'.
> 18 error This is most likely a problem with the tutorial package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     webpack-dev-server --hot
> 18 error You can get information on how to open an issue for this project with:
> 18 error     npm bugs tutorial
> 18 error Or if that isn't available, you can get their info via:
> 18 error
> 18 error     npm owner ls tutorial
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

why tips this

**Comment by MrOutis** [comment]
no idea, dude, maybe it is related to this issue: https://github.com/reactjs/react-router-tutorial/issues/171

**Comment by timdorr** [comment]
Make sure you've run `npm install`. It's hard to tell on Windows, but it looks like `webpack-dev-server` isn't installed.

**Comment by herberton** [comment]
I have the same problem... Someone help us?
I'm using Windows 7, nodejs v6.3.0, npm 3.10.3, Angular 2.0.0-rc.4 and WebPack 1.13.1

**Comment by volash86** [comment]
@herberton Hello, do you finished the issue?

**Comment by herberton** [comment]
No I don't, but I didn't have the same problem with the Linux. So now, after that I am working with Ubuntu.
