### ISSUE TITLE
12-navigating .push(path) keeps adding to URL

### ISSUE THREAD

**Issue by justin-calleja** [reactjs/react-router-tutorial#177]
Hi,

[lesson 12](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/12-navigating) in the tutorial uses `browserHistory` or `this.context.router` to `.push(path)`, both of which keep adding to the URL e.g.

adding hello/world gives a URL of: `http://localhost:8080/repos/hello/world`
adding it again: `http://localhost:8080/repos/hello/repos/hello/world`

(refreshing now breaks).

Another e.g. if you use the form with a starting point of `http://localhost:8080/repos/reactjs/react-router`

you get: `http://localhost:8080/repos/reactjs/repos/hello/world`

**Comment by tychovk** [comment]
Can you paste your `Repos.js`?

**Comment by justin-calleja** [comment]
Hi tychovk, sorry for the late reply. My Repo.js should have the changes described in the lesson:

```js
import React from 'react'
import NavLink from './NavLink'
import { browserHistory } from 'react-router'

export default React.createClass({
  // contextTypes: {
  //   router: React.PropTypes.object
  // },

  handleSubmit(event) {
    event.preventDefault();
    const userName = event.target.elements[0].value;
    const repo = event.target.elements[1].value;
    const path = `repos/${userName}/${repo}`
    console.log(path);
    browserHistory.push(path);
    // this.context.router.push(path);
  },

  render() {
    return (
      <div>
        <h2>Repos</h2>
        <ul>
          <li><NavLink to='/repos/reactjs/react-router'>React Router</NavLink></li>
          <li><NavLink to='/repos/facebook/react'>React</NavLink></li>
          <li>
            <form onSubmit={this.handleSubmit}>
              <input type="text" placeholder="userName" /> / {' '}
              <input type="text" placeholder="repo" />{' '}
              <button type="submit">Go</button>
            </form>
          </li>
        </ul>
        {this.props.children}
      </div>
    );
  }
});
```

Same result should happen if `browserHistory.push` is commented out and commented parts uncommented (i.e. the 2nd method).

**Comment by tychovk** [comment]
Yup, it's this specific part:
`    const path = `repos/${userName}/${repo}`
should be changed to:
`    const path = `/repos/${userName}/${repo}`

The devil was in the dash.

**Comment by justin-calleja** [comment]
@tychovk the best! Cheers, I should have copy/pasted :sweat_smile:
