### ISSUE TITLE
Clone this repo is not a tutorial.

### ISSUE THREAD

**Issue by Rojuinex** [reactjs/react-router-tutorial#185]
As the title says, telling someone to "clone this repo and poke around" (exact verbiage used in your readme) is NOT a tutorial.  If I wanted to poke around at code I would have inspected source on your website not Google searched "react-router tutorial".  I'm looking for a tutorial, you know a walk though, not a revere engineering session.  Perhaps this repo would be better named react-router-examples as to not mislead people?

**Comment by garotosopa** [comment]
I think you've misunderstood that instruction. When it says to "poke around" it's just "to see how they're using webpack and npm scripts to run the app". At the bottom of that very page there is the link "Next: Rendering a Router", which guides you by the hand on the walk through with clear instructions that you're looking for. You can take a look at every step in the [lessons](https://github.com/reactjs/react-router-tutorial/tree/master/lessons) directory.

**Comment by timdorr** [comment]
@Rojuinex You don't have to look through the code in the first lesson if you don't want to. It's an optional thing that the readme is inviting you to do. This is a hands-on tutorial series, so sorry, but you're going to have to get your hands dirty. This provides some of the best learning experience though.
