### ISSUE TITLE
about  component

### ISSUE THREAD

**Issue by KingChow** [reactjs/react-router-tutorial#186]
As follows:
"\<Route path='/board/:boardName' component={Board}>
            \<Route path='/board/:boardName/:**itemName**'  component={  **itemName**  }>\</Route>
\</Route>"

How to set component according to the value  of itemName in path?

**Comment by timdorr** [comment]
You can use the `getComponent` prop instead. It takes a function that can dynamically return the component to use.

**Comment by KingChow** [comment]
Thanks ！
