### ISSUE TITLE
Router from context in TypeScript

### ISSUE THREAD

**Issue by galvesribeiro** [reactjs/react-router-tutorial#189]
Hey guys,

I'm asking here since the channel on discord looks like a deadland...

So, I'm trying to follow https://github.com/reactjs/react-router-tutorial/tree/master/lessons/12-navigating by using the context to receive a Router object but can't see how to do that in TypeScript...

Can anyone suggest anything?

Thanks

**Comment by timdorr** [comment]
That should be similar to how you would do `propTypes`. I'm not a normal TS user, but I believe you can use them the same way with `React.createClass`. If you're using ES2015 classes instead, just mark the property as `static`.

**Comment by galvesribeiro** [comment]
@timdorr so you are saying that our TypeScript class (which transpile to ES6) should just declare `public static router:Router;` and it is injected?

**Comment by timdorr** [comment]
No, something like this:
```js
    static contextTypes = {
        router: React.PropTypes.func.isRequired
    }
```

**Comment by galvesribeiro** [comment]
I added that and not the build is broken...
![image](https://cloud.githubusercontent.com/assets/4714040/16472867/6f7bb550-3e3e-11e6-8f4f-c9e00d9e3106.png)
:(

**Comment by timdorr** [comment]
I'm sorry, I'm not a heavy TS user. This tutorial is built around plain ES2015 Javascript, so you'll have to get help elsewhere. But I know other people are using it, so it's certainly possible.
