### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by JonatronLeon** [reactjs/react-router-tutorial#192]
Hi, I was trying to understand server side rendering for react-router, so I tried lesson 14 to compare what I've done with what you've done, and I seem to be having the same problem. Doing a fresh npm install, then npm start on lesson 14, I get a 404 trying to reach http://localhost:8080/. Any ideas as to what might be going on?

**Comment by stonebraker** [comment]
I encountered the same issue. Lesson 14 runs as expected when using `NODE_ENV=production npm start`, but not in development mode using `npm start`. Understanding that this isn't a tutorial about server side rendering, I will say the routing tutorials are some of the best written tutorials I've come across in a long time (not to mention the Router itself). It would be wonderful to see this team produce some tutorials about tooling and configuration for developing production level React applications based on their own experience and recommendations. This routing tutorial would serve as an excellent starting point. :-)
