### ISSUE TITLE
Incorrect run command on windows

### ISSUE THREAD

**Issue by luksprog** [reactjs/react-router-tutorial#193]
In lesson *11-productionish-server* the readme says that windows users should use *SET NODE_ENV=production npm start*, this will not work as it will simply set the NODE_ENV to "production npm start". The command should be **SET NODE_ENV=production&& npm start**(no space between production and &&). Also, for powershell windows users the command is *$env:NODE_ENV="production"; npm start*.

**Comment by timdorr** [comment]
This has been fixed.
