### ISSUE TITLE
lessons-02:  blank screen - no errors

### ISSUE THREAD

**Issue by lordKnighton** [reactjs/react-router-tutorial#194]
I'm running my code along with the lessons:02 I have no errors, but when i take a trip to localhost:8080
I get a blank screen, lesson 01 worked perfectly it rendered as expected on client side. 

but no such luck with lesson 02

`index.js`
```js
import {Router, Route, hashHistory} from 'react-router'
import About from './modules/About'
import Repos from './modules/Repos'

render ((
  <Router history={hashHistory} >
    <Route path="/" component={App} />
    <Route path="/repos" component={Repos} />
    <Route path="/about" component={About} />
  </Router>
), document.getElementById('app'))

```

`App.js`
```js
import React from 'react'

export default React.createClass({
  render() {
    return <div>Hello, React Router!</div>
  }
})

```

---

![screen shot 2016-07-06 at 12 21 30 pm](https://cloud.githubusercontent.com/assets/1773260/16631491/49c63124-4374-11e6-818a-872758779efe.png)

**Comment by luksprog** [comment]
Did you check the console for error? For example I don't see anywhere in _index.js_ the import for _App_,  **import App from './modules/App'**

**Comment by ChewyJetpack** [comment]
I also have this same issue. No console errors, App is imported correctly. Blank screen, App component not being rendered in source.

**Comment by omnibusinc** [comment]
ChewyJetpack, can you post your code?  
lordKnighton above does _not_ have App imported into index.js, so that's likely his issue.

**Comment by ChewyJetpack** [comment]
My bad - turned out to be a syntax error on my part.

**Comment by mariusz-blaszczak** [comment]
I had the same issue when I didn't import `Link` from react-router. Strange that it didn't raise an error.
