### ISSUE TITLE
Lesson 13 issue with 

### ISSUE THREAD

**Issue by cata-libuy** [reactjs/react-router-tutorial#195]
Hi, After I run the server, I'm getting this erros in console (the folders says 10, because I started the lesson from there, but It's same as 13 right now).

```
Hash: efc6d9c205c212b3dcb3
Version: webpack 1.13.1
Time: 8604ms
           Asset     Size  Chunks             Chunk Names
server.bundle.js  11.2 kB       0  [emitted]  main
    + 14 hidden modules
/home/cata/Nursoft/vvn/repos/examples/react-router-tutorial-master/lessons/10-clean-urls/node_modules/express/node_modules/serve-static/index.js:40
    throw new TypeError('root path required')
          ^
TypeError: root path required
    at Function.serveStatic (/home/cata/Nursoft/vvn/repos/examples/react-router-tutorial-master/lessons/10-clean-urls/node_modules/express/node_modules/serve-static/index.js:40:11)
```
The server behaves as the previous lesson, I mean, If I navigate to localhost:8080 I see the app rendering js as always. If I disable js from the web inspector, I see only a blank page, so the server is not rendering the app.

Sorry for my english.

**Comment by timdorr** [comment]
Make sure you removed the index.html file. The server will read and send that file if it's provided, which is likely blank if you copied from lesson 10.
