### ISSUE TITLE
Lesson 11: cannot run dev server

### ISSUE THREAD

**Issue by dimsav** [reactjs/react-router-tutorial#203]
First of all, a big thanks for this amazing tutorial. 

After applying the changes according to the lesson 11, we I the following error for the dev server command only.

To make sure it wasn't my bad I ran the web server on a fresh install of lesson 12.

The production server works fine.

<img width="663" alt="image 2016-07-12 at 22 33 54" src="https://cloud.githubusercontent.com/assets/1785686/16780841/1ce09c64-4881-11e6-8d9d-51d78a4d915f.png">

**Comment by dimsav** [comment]
Restarting my computer fixed the issue. It turns out was getting this error for every lesson.

**Comment by dimsav** [comment]
Again, replying to myself in case somebody has this issue.

Updating node fixed the issue. It turned out the version I had (0.10) was too old.

**Comment by echodis** [comment]
Hello, It seems that I have the similar problem as yours.
I want to know which version of node solves your problem ?
thanks a lot !

**Comment by dimsav** [comment]
hi @echodis after updating node I have v6.3.0.
