### ISSUE TITLE
[Lesson-12] code missed in tutorial of README.md

### ISSUE THREAD

**Issue by veah** [reactjs/react-router-tutorial#204]
### Please check the READEME.md. A part of code is missed.

These codes below should be added in `repo.js`  or  the path we submitted would not show in the right way.The code is already included in `repo.js` of Lesson-12's demo but **not mentioned in the tutorial**.
```
render() {
   const {userName,repoName} = this.props.params
   return (
       <div>
           <h2>{userName} / {repoName}</h2>
        </div>
     )
}
```

I don't speak English so if there is somewhere I said wrong please don't mind.

**Comment by timdorr** [comment]
A PR to add this would be great.

**Comment by veah** [comment]
I've opened a PR ,please check out. @timdorr
