### ISSUE TITLE
Bug in lesson 01-setting-up

### ISSUE THREAD

**Issue by codyromano** [reactjs/react-router-tutorial#205]
I followed the steps to clone the repo, install and start the node server, but the "Hello world" message doesn't appear and I get the following console error: 

`bundle.js:59 Uncaught TypeError: Cannot read property 'replace' of null`

This is line 59:

`var scriptHost = scriptElements[scriptElements.length-1].getAttribute("src").replace(/\/[^\/]+$/, "");`

**Comment by timdorr** [comment]
Disable any extensions you have running in your browser. They seem to be causing the issue with recent versions of webpack-dev-server.

**Comment by sabertazimi** [comment]
Thx.
