### ISSUE TITLE
Add path="*" lesson

### ISSUE THREAD

**Issue by j0hnsmith** [reactjs/react-router-tutorial#207]
This tutorial is great, thanks for creating it. I was looking for a catch all route for 404 behaviour and realised it's not covered by any of the lessons, it would be a useful addition.

eg `<Route path="*" component={NoMatch}/>`

**Comment by timdorr** [comment]
The catch-all route doesn't provide a true 404 response on the server side. It's a known problem area in React Router that there isn't currently a good answer for. But if you want to add it to the examples, a PR would be great. Thanks!
