### ISSUE TITLE
Lesson 13: why "using something like babel/register is not fit for production use"?

### ISSUE THREAD

**Issue by DimitryDushkin** [reactjs/react-router-tutorial#210]
Why it doesn't fit? Please explain.

I've found discussion about this topic here — http://stackoverflow.com/questions/31661310/using-requirebabel-register-vs-transpiling-the-code-before-running. There is opinion that actually babel-registry is okay for production.

**Comment by timdorr** [comment]
Babel register means all your code is transpiled at startup. This can slow your app's boot time, which may or may not be good for your app. A better way to do this is to pre-transpile your code before shipping to production, alongside any production builds that you do for your frontend code.

**Comment by DimitryDushkin** [comment]
So it is fit for production use if startup time is not significant factor. I think this note might be useful in lesson text.
