### ISSUE TITLE
Code missing for lesson 02-rendering-a-route

### ISSUE THREAD

**Issue by mdecaffmeyer** [reactjs/react-router-tutorial#213]
Hi,

The code for lesson 02-rendering-a-route is identical to lesson 01-setting-up.

Could you please tell me where to find the code?
Thank you

**Comment by fastestOrange** [comment]
It is intended to be the same code. Lesson.1 simply gets you started and makes sure everything is installed. Lesson 2 is the same starting point but gets into the router. Good luck!
