### ISSUE TITLE
Suggestion: onEnter hooks

### ISSUE THREAD

**Issue by renarsvilnis** [reactjs/react-router-tutorial#24]
Hi,
I'd like to submit a suggestion. I feel like an important part of using react router is `onEnter` hooks which hasn't been explained in much detail. An example with restricted routes would be showcase the `onEnter` hook in the most practical way.

**Comment by mijikim** [comment]
I agree with this suggestion. It was bit difficult trying to understand onEnter hooks as I was trying to migrate from statics:{ willTransitionTo: {}} provided by react-router@0.13.3 to onEnter hook in newer version of react-router. A detailed example on how to use onEnter hook provided by the team would have been helpful. 
Thank you!

**Comment by timdorr** [comment]
A PR would be great!
