### ISSUE TITLE
Lesson 1-setting-up npm start error

### ISSUE THREAD

**Issue by 5SMNOONMS5** [reactjs/react-router-tutorial#251]
After run **npm start** , it appear this error ....

![screen shot 2016-10-17 at 4 49 58 pm](https://cloud.githubusercontent.com/assets/8379901/19431151/d558baf2-9489-11e6-9de3-198857be808d.png)

**Comment by Andersos** [comment]
There are missing some lines from the error message. What is above the picture you attached?
It might be that you are missing a dependency so you want to `npm install` whatever dependency you are missing.

**Comment by 5SMNOONMS5** [comment]
sorry for late response , this is complete error page
![image](https://cloud.githubusercontent.com/assets/8379901/19633241/d56485fa-99e1-11e6-9857-5faae95bb810.png)

**Comment by Andersos** [comment]
So this error message "EADDRINUSE" means that something is already running on port 8080.

You can either change the port to another address or you can try and kill whatever is already running.

You can kill it by doing:
`lsof -i :8080`

Then when you have the pid run:
`kill -9 <PID>`

**Comment by 5SMNOONMS5** [comment]
@Andersos  thx very much .. it now work for me !! ^^
