### ISSUE TITLE
Issue running npm start after npm install - lesson 1

### ISSUE THREAD

**Issue by MarvDann** [reactjs/react-router-tutorial#257]
Currently having an issue running npm start after npm install.
The problem is after I have cloned the repo and run npm install in the lesson 1 directory
When I run npm start I get the following error log.

```
D:\projects\learning\react-router-tutorial\lessons\01-setting-up>npm start

> tutorial@1.0.0 start D:\projects\learning\react-router-tutorial\lessons\01-setting-up
> webpack-dev-server --inline --content-base .

events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1225:19)
    at listen (net.js:1274:10)
    at net.js:1383:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! tutorial@1.0.0 start: `webpack-dev-server --inline --content-base .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tutorial@1.0.0 start script 'webpack-dev-server --inline --content-base .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --content-base .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tutorial
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tutorial
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\learning\react-router-tutorial\lessons\01-setting-up\npm-debug.log
```

Operating system: Windows 10 Home.

**Comment by Andersos** [comment]
So it looks like you already have something running on 127.0.0.1:8080. Try finding it and turning it off before running `npm start` again.

**Comment by MarvDann** [comment]
Thanks Andersos - I ran a command window in Administrator mode and ran the command
netstat -anob
This gave me a list of port usage and I could see 8080 was being used but it wouldn't tell me what was using it. Next step was try to kill the process using taskkill /pid <process_id_goes_here>
Computer said "NO!"...  access denied. 

Next step I tried this in a command window...
telnet 127.0.0.1 8080 which opened the telnet client then I typed
GET / HTTP/1.1 and hit return twice and it gave me some information that suggested it was t do with IIS with the headers in the response.

Next Step was to check IIS and click on the Sites node and expand the window so I could see all the bindings and which ports were bound to. This revealed that TFS was the culprit! 
I removed the TFS website from IIS as I dont use it anymore and it all worked!

Thanks for the heads up I was beginning to lose faith!

**Comment by Andersos** [comment]
Im glad you figured it out. I'm sorry I should have told you that you can change the port that your run the demo on if that would have been easier. It is good that you added the steps you took as well so others that might find this issue also can get some help.
