### ISSUE TITLE
Router Tutorial , Nested Routes 

### ISSUE THREAD

**Issue by daslicht** [reactjs/react-router-tutorial#260]
reference : https://github.com/reactjs/react-router-tutorial/tree/master/lessons/04-nested-routes
Hi,
I have the following structure :
```
index.jsx
     Main
         Details
```

index.jsx:
```
    <Router history={hashHistory}>
        <Route path="/" component={Main}>
            <Route path="/details" component={Details}/>
        </Route>
    </Router>,
```

main.jsx:
```
render() {
    return (  
      <div>
        <ul>
          <li><Link activeStyle={{ color: 'red' }} to="/">Main</Link></li>
          <li><Link activeStyle={{ color: 'red' }} to="/details">Details</Link></li>
        </ul>

        {this.props.children}
        
      </div>
    );
  }
```
How to add content now for Main (path "/") please? 
Do I need to push it into the properties ?

**Comment by Andersos** [comment]
You want to make a new entry in your index.jsx file that is an [IndexRoute](https://github.com/ReactTraining/react-router/blob/master/docs/guides/IndexRoutes.md).

**Comment by daslicht** [comment]
Thank you !
