### ISSUE TITLE
What is the point of hashHistory?

### ISSUE THREAD

**Issue by developer239** [reactjs/react-router-tutorial#278]
What is the point of hashHistory? Why don't you show browserHistory instead? This step is unnecessary.

**Comment by tibuurcio** [comment]
Your app won't work properly with browserHistory if you host it on Github pages, for example. That's cause to use browserHistory you need to have server-side configuration, as stated in [Lesson 2](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/02-rendering-a-route). hashHistory comes in handy when you want to have only frontend code in your app.

**Comment by developer239** [comment]
I did not know that. However it does not change the fact that it might be confusing for beginner programmers. Hash history seems totally pointless to me. I can't think of any situation where I would prefer hash history over browser history. I would rather spent 5 minutes more setting up server that using /#/ugly-uri?%fwasdfa. :(
