### ISSUE TITLE
Lesson 13 - path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by calebmichaelsanchez** [reactjs/react-router-tutorial#28]
I got this error when setting up server rendering.
It relates to this line in server.js. 

```
app.get('*', function (req, res) {
  res.sendFile(path.join(__dirname, 'public', 'index.html'))
})
```
In the express docs it shows you can pass the filename and an options object specifying the root of the project.

This is the code that got it working for me. 
```
app.get('*', function (req, res) {
  res.sendFile("index.html", { root: path.join(__dirname, 'public') })
})
```

I'd be happy to make a pull request, though I've never made one before. 

Thanks for the tutorial by the way. Very helpful.

**Comment by jahmaiosullivan** [comment]
You must have saved me at least an hour of research. Thank you!
