### ISSUE TITLE
Fails on my system: npm ERR!     webpack-dev-server --inline --content-base .

### ISSUE THREAD

**Issue by anupritawayangankar** [reactjs/react-router-tutorial#283]
Hello,

I have followed below steps : 
git clone https://github.com/reactjs/react-router-tutorial
cd react-router-tutorial
cd lessons/01-setting-up
npm install
npm start

but im getting error which i have attached.
Please check into this.

Thanks.

![error-log](https://cloud.githubusercontent.com/assets/20037694/22454545/952c4680-e7ac-11e6-9558-832a6b3bd456.png)

**Comment by codyloyd** [comment]
I'm on linux but getting very similar errors.. lesson 1 and 2 worked for me but 3 is crashing.  I deleted the whole directory and re-cloned it to no avail.

**Comment by qianch3n** [comment]
If you are using the Windows, open the task manager.  Find the `Node.js: Server-side JavaScript ` process. Kill it and then try `npm start` again.

**Comment by EulerTourist** [comment]
Getting the same error on macOS

**Comment by sasha-lin** [comment]
@EulerTourist  In the first step, you need npm install
