### ISSUE TITLE
example code is not map to corresponding lesson

### ISSUE THREAD

**Issue by yihaoye** [reactjs/react-router-tutorial#318]
I use "git clone https://github.com/reactjs/react-router-tutorial" to download the tutorial, however some example codes seem not map to their lesson. Some example codes are map to last lesson.

For example:
react-router-tutorial/lessons/02-rendering-a-route have the same code with react-router-tutorial/lessons/01-setting-up
code in react-router-tutorial/lessons/03-navigating-with-link is for lesson 2
code in react-router-tutorial/lessons/04-nested-routes is for lesson 3
...

please have a check with all example code and modify them.

**Comment by zainulabidin302** [comment]
lesson 01 is introductory and there are no code changes in the first lesson. code changes start from lesson 02.

03 and 04 ->  module/App.js files are not same and according to the flow of tutorial.

I don't see any redundancy.
