### ISSUE TITLE
06 params.md

### ISSUE THREAD

**Issue by laeg** [reactjs/react-router-tutorial#32]
Uncaught ReferenceError: Home is not defined

```
render((
  <Router>
    <Route path="/" component={App}>
      <IndexRoute component={Home}/>
      <Route path="/repos" component={Repos}/>
      {/* add the new route */}
      <Route path="/repos/:userName/:repoName" component={Repo}/>
      <Route path="/about" component={About}/>
    </Route>
  </Router>
), document.getElementById('app'))
```

**Comment by laeg** [comment]
Was this meant to be left in or is there a component missing?

**Comment by rynslmns** [comment]
I ran into the same issue. I resolved it by Routing it to Repos instead of Home and it had the desired behavior. But not sure why it pointed to a component that was yet defined.

**Comment by keul** [comment]
Mmmphf... this tutorial is full of bugs

**Comment by ryanflorence** [comment]
Sorry about the bugs, it was written really quickly. I also made a bad choice with the repo "git history as feature" making pull requests hard to deal with, fixing it soon though.
