### ISSUE TITLE
Lesson 11 missing express on dependencies

### ISSUE THREAD

**Issue by fhelwanger** [reactjs/react-router-tutorial#4]
First of all, thank you so much for this tutorial! It's very well written and easy to follow.

I think that on [lesson 11](https://github.com/rackt/react-router-tutorial/blob/start/lessons/11-productionish-server.md) `express` could be installed along with `if-env` and `compression`.

I didn't make a PR because your commit history is very organized, so I don't know how to proceed.

**Comment by deviantony** [comment]
+1
