### ISSUE TITLE
Add client/server-side rendering of dynamic content?

### ISSUE THREAD

**Issue by ivanakimov** [reactjs/react-router-tutorial#48]
This is super awesome, thanks for making this.

If there was one thing that would make this tutorial 11/10 imo, it would be fetching dummy data via an AJAX call **and** figuring out how to make the same data render on the server after refreshing:

1. User navigates to a specific repo, an ajax call is made to get the number of open issues for example.
2. But if the user refreshes the page, then the number of issues is already rendered by the server (no need for an ajax call).

That way dynamic content is also crawlable, not just static templates. Of course this is kinda useless in this specific scenario, but would give a good idea for devs on how to server-side render not only static content, but also dynamic.

**Comment by timdorr** [comment]
Data fetching isn't covered at all. It's arguable you should learn something like Redux to manage that. I think that sort of thing might be out of scope on this tutorial. 

However, adding it to the "what's next" tutorial might be a good idea. A PR for that would be great!
