### ISSUE TITLE
Make every subject it's own folder

### ISSUE THREAD

**Issue by ryanflorence** [reactjs/react-router-tutorial#89]
The way the repo is designed is dumb. Any changes require the entire history of the project to be changed.

The idea was you could `git checkout` to every lesson, but that makes PRs pretty much impossible to accept.

Instead, every lesson should be a folder with a fully runnable app, not a commit in the git history.

**Comment by florida** [comment]
I can take this one on. For the structure, I'm just mostly going to copy the structure of ReactJSTraining

**Comment by ryanflorence** [comment]
Awesome, thanks :)

**Comment by ryanflorence** [comment]
I think it should be different than the training repo, instead of one big webpack config, each lesson should be its own runnable app, with its own webpack config (I mean, you can share everything except the entry).

There will be a ton of duplicate code, and that's fine.

It'll look something like:

```
├── code
│   ├── 01-setting-up
│   │   ├── index.js
│   │   ├── modules
│   │   └── webpack.config.js
│   ├── 02-rendering-a-arouter
│   │   ├── index.js
│   │   ├── modules
│   │   └── webpack.config.js
│   └── 03-navigating-with-link
│       ├── index.js
│       ├── modules
│       └── webpack.config.js
└── lessons
    ├── 01-setting-up.md
    ├── 02-rendering-a-router.md
    └── 03-navigating-with-link.md
```

And then you should be able to

```
cd code/01-setting-up
npm start
```

Of course, if you're doing the whole tutorial you don't have to ever leave the first lesson's code, but if you want to jump to a different lesson you just go to that directory.

This way PRs can be merged easily.

**Comment by florida** [comment]
Awesome! thank you! :dancer:

**Comment by ryanflorence** [comment]
I'd probably

```
# checkout "Lesson 02 Final"
git checkout 9fc24d36010489dc2f51cc291309cb9c197b07ed
cd ../tmp
# which is actually the start of lesson 03
cp -R ../react-router-tutorial 03-navigating-with-link
```

And do that for every commit here

https://github.com/reactjs/react-router-tutorial/commits/master

**Comment by andrewcoelho** [comment]
Shucks, I should've checked here first to see someone else was working on it. I already submitted a PR that fixes this issue, but won't mind at all if you reject it in favor of @florida solution.

**Comment by florida** [comment]
I just saw @andrewcoelho's comment, it looks like your PR is a bit more polished than mine. I'm okay with that being merged! Good job on the PR! :dancer: :+1:

**Comment by andrewcoelho** [comment]
@florida thanks! Really didn't mean to undercut you. I guess @ryanflorence can decide what the best path forward is, if, for example, he would prefer the code separated from the lesson text as per the comment he posted above.
